### ISSUE TITLE
Too much modification of server.js is required 

### ISSUE THREAD

**Issue by CharlesTBetz** [dm-academy/node-svc#18]
IP addresses, ports should not be hard coded into the code. Need a different solution.

**Comment by CharlesTBetz** [comment]
so @mek88 @jnghn1 @smileyspoon you are the 3 who have gotten thru lab 03 (I think). What do you think about this issue? How can we make this easier?

**Comment by mek88** [comment]
My first thought was env variables as well. I can see in the kube docs where you can set these in the deployment file, but it seems like that just shifts the problem to a different location (although one that is more consistent with the rest of the lab).

AWS usually has a metadata endpoint you can call to get into about the box you're running on. I've been looking to see if Google has the equivalent for that cluster service - something that could be run as userdata when the host spins up, or (less desirable) as part of the server.js code when it's run.

**Comment by mek88** [comment]
Might be worth playing with [configmaps ](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data)and some additional kube commands to generate the map and use a literal that comes from a gcloud terminal command.

**Comment by jnghn1** [comment]
In my case, when I got lost in Lab practice, I read Lab instruction several times and review my commands step by step comparing the instruction. The instruction was not easy; however, it includes all information that I need to change the code carefully. When I got error messages, I tried to interpret and understand the meaning of error messages, and search Google. The error message had key information that I entered the wrong information. This is how I could solve lab 03. I think before we start this kind of lab instruction, we need to understand the meaning and role of variables in files. We must submit two screenshots. The pipeline setting was also not easy, however, following the steps was helpful.
________________________________

**Comment by CharlesTBetz** [comment]
> My first thought was env variables as well. I can see in the kube docs where you can set these in the deployment file, but it seems like that just shifts the problem to a different location (although one that is more consistent with the rest of the lab).
> 
> AWS usually has a metadata endpoint you can call to get info about the box you're running on (including public IPs). I've been looking to see if Google has the equivalent for that cluster service - something that could be run as userdata when the host spins up, or (less desirable) as part of the server.js code when it's run.

I am OK with folks having to create one file that contains all the configurable stuff, that becomes the key assignment piece and there's then no question about what belongs in source control. 

I 've had some indication that Helm charts also solve this but really not sure want to bring them in to an intro course.

**Comment by CharlesTBetz** [comment]
The environment variable already exists within the Docker container when created by Kubernetes. See https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

Added `const arrNodes = [ process.env.NODE_SVC_PUBLIC_SERVICE_HOST  ];` as option.
